MOVIES = [
    "Demystifying Data Science: No Big Dill",
    "Once Upon a Thyme in America",
    "Sage Advice from a Data Scientist",
    "Seasoned Greetings",
    "A Little Chili Outside",
    "Treading Gingerly",
    "Keep Calm and Curry On",
    "Captain Flask and the Ginger Templates",
    "Catch Me if you Cayenne",
    "We're Mint to be Together",
    "Getting Jalapeño Business",
    "Life After Spiced: Mildly Disappointing",
    "Don't Stop Bay Leafing",
    "Oregano Sin",
    "Herb Your Enthusiasm",
    "Part and Parsely of being a Data Scientist",
    "Fennel Vision",
    "Naive Basil Classifier",
]
